HDDS-4496. Separate client and server2server GRPC services of datanode
apache/ozone pull request #1635
Opened 2020-11-30 13:47 UTC by elek

## What changes were proposed in this pull request?

Today both the closed-container-replication service and datanode client service are exposed on the same datanode port which makes it impossible to use different network configuration (like mutual TLS).

In this patch I propose to separate the two services and use two network ports.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4496

## How was this patch tested?

Tested the replication with local docker-compose cluster (adding keys, closing container, waiting for replication)

2020-12-07 18:21 UTC, adoroszlai commented
> Containers supposed to be visible under /tmp

I think this depends on `hdds.datanode.dir` setting.  In `ozone` compose env the container was replicated by default to `/data/hdds`.  Got it to replicate to `/tmp` with: `ozone freon -Dhdds.datanode.dir=/tmp cr -t 1`.

On another note, trying to run `ozone freon cr` the second time leads to:

```
[main] ERROR volume.MutableVolumeSet: Failed to parse the storage location: /tmp
java.io.IOException: Volume is in an INCONSISTENT state. Skipped loading volume: /tmp/hdds
  at org.apache.hadoop.ozone.container.common.volume.HddsVolume.initialize(HddsVolume.java:225)
```

Is this expected?  Do you know a workaround for that?

2020-12-10 23:54 UTC, jojochuang requested changes
Overall looks good. Just some nits

2020-12-10 23:54 UTC, jojochuang commented on hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/ClosedContainerReplicator.java
> +        //if datanode is specific replicate only container if has a replica.
specified.

2020-12-10 23:54 UTC, jojochuang commented on hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/ClosedContainerReplicator.java
> +        if (datanode.equals("") || datanodeUUIDs.contains(datanode)) {
typically ppl use String.isEmpty() instead.

2020-12-10 23:54 UTC, jojochuang commented on hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/ClosedContainerReplicator.java
> +    if (fakeDatanodeUuid.equals("")) {
String.isEmpty()?

2021-01-06 11:18 UTC, elek commented
> Is this expected? Do you know a workaround for that (other than deleting /tmp/hdds)?

I can implement an automatic delete, but I think it's more safe to live it for the users. It seems to be more safe to fail when the directory is not empty (harder to understand what was downloaded) and ask users to delete the dir.

But I am not sure, can be convinced.

2021-01-06 11:22 UTC, elek commented
@jojochuang Thanks for the suggestions, I updated the branch with them.

2021-01-06 11:22 UTC, adoroszlai commented
> I can implement an automatic delete, but I think it's more safe to live it for the users. It seems to be more safe to fail when the directory is not empty (harder to understand what was downloaded) and ask users to delete the dir.

Agreed.  Can you add a comment somewhere to remind users to delete the dir in case of this error?

2021-01-06 15:48 UTC, elek commented
> > I can implement an automatic delete, but I think it's more safe to live it for the users. It seems to be more safe to fail when the directory is not empty (harder to understand what was downloaded) and ask users to delete the dir.
> 
> Agreed. Can you add a comment somewhere to remind users to delete the dir in case of this error?

Sure. I added a check to return with more meaningful error. (5aa2fcce08dc37ce5497547ad48c5452425cb28f)

2021-01-08 18:01 UTC, adoroszlai approved these changes
Thanks @elek for updating the patch.

2021-01-10 07:36 UTC, elek commented
Merged. Thanks the review @adoroszlai and @jojochuang

2021-01-10 07:36 UTC, merged