HDDS-4593. Refine IAccessAuthorizer interface to do recursive ACL check on a path
apache/ozone pull request #1790
Opened 2021-01-13 10:58 UTC by rakeshadr

## What changes were proposed in this pull request?

The idea/proposal is to refine #checkAccess interface by giving "recursive" hint and make only one single call during recursive delete or list operations. Now, the implementation classes(native or external entity) can do recursive logic in an optimized way.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4593

## How was this patch tested?

Modified existing UTs to check the flag values. Will add more test cases along with atomic delete ops.

2021-01-18 16:19 UTC, mukul1987 requested changes
I think we also need changes to use or set the resrusiveAccessCheck flag in our code. Will that be covered as part of another patch ?

2021-01-19 11:39 UTC, rakeshadr commented
> I think we also need changes to use or set the resrusiveAccessCheck flag in our code. Will that be covered as part of another patch ?

Thanks @mukul1987 for the reviews. This PR is targeting to the master branch and I am planning to do the recursiveCheck=true on the feature branch code. Once this PR is merged then I will rebase the feature branch with master and then will do the settings along with HDDS-4691 task.

Hope this makes sense to you.

2021-01-19 19:56 UTC, xiaoyuyao approved these changes
LGTM, +1 pending CI.

2021-01-20 05:29 UTC, rakeshadr commented
> LGTM, +1 pending CI.

Thanks @xiaoyuyao for the reviews. CI failure is unrelated to the patch, anyway I've triggered another build.
I could see HDDS-4693 is raised to fix TestContainerStateMachine failure.

2021-01-20 13:06 UTC, merged

2021-01-20 13:09 UTC, rakeshadr commented
Thank you @mukul1987 , @xiaoyuyao for the reviews!