HDDS-5368. Add CLI command: ozone admin namespace summary
apache/ozone pull request #2565
Opened 2021-08-23 19:19 UTC by yuangu002

## What changes were proposed in this pull request?

Add the ozone admin shell command ozone admin namespace summary

From the design doc:

$ ozone admin namespace summary --all /vol1/bucket1/MyDir

Entity Type : Directory
Directories : 1
Keys : 10

DU
  Size  DiskUsage   Path
  21G     63G          /volume1/bucket1
  5G      15G          /volume1/bucket2

File Size Distribution
  1KB - 2KB - 50% (5)
  2KB - 4KB - 50% (5)

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-5368

## How was this patch tested?

Configs:
```
ozone sh volume create /vol1
ozone sh volume create /vol2
ozone sh bucket create /vol1/bucket11
ozone sh bucket create /vol1/bucket12
ozone sh bucket create /vol2/bucket21
ozone sh bucket create /vol2/bucket22
ozone sh key put --replication=THREE /vol1/bucket11/key1 README.md
ozone sh key put --replication=THREE /vol1/bucket11/key2s README.md
ozone sh key put --replication=THREE /vol1/bucket11/dir1/key3 README.md
ozone sh key put /vol2/bucket21/key4 CONTRIBUTING.md
ozone sh key put /vol2/bucket21/key5 CONTRIBUTING.md
ozone sh key put /vol2/bucket22/key6 README.md
ozone sh key put --replication=THREE /vol2/bucket22/dir22/key7 LICENSE.txt
ozone sh key put /vol1/bucket12/dir1-1/key8 README.md
ozone sh key put /vol1/bucket12/dir1-2/key9 CONTRIBUTING.md
ozone sh key put --replication=THREE /vol1/bucket12/directKey README.md
```
Usage:
`ozone admin namespace [summary | du | quota | dist] [-options] <path>`

Example: `ozone admin namespace summary /`
![Screen Shot 2021-08-23 at 3 12 10 PM](https://user-images.githubusercontent.com/53324985/130504249-fd3592f2-fe18-45b6-9c7d-ebb0ffa28c3b.png)

(du with replica)
`ozone admin namespace du --replica /`
![Screen Shot 2021-08-23 at 3 14 28 PM](https://user-images.githubusercontent.com/53324985/130504531-b06bf23c-9eb7-4d1b-bcb0-942ab8a681d6.png)

(du with listing direct keys)
ozone admin namespace du --replica --file /vol1/bucket12
![Screen Shot 2021-08-23 at 3 17 30 PM](https://user-images.githubusercontent.com/53324985/130504859-5b89a128-97ff-447d-9224-d95b90bb7d40.png)

Other option usage for `du`:
![Screen Shot 2021-08-23 at 3 13 08 PM](https://user-images.githubusercontent.com/53324985/130504353-733f8412-742d-491f-a09f-99655db95188.png)

`ozone admin namespace quota /`
![Screen Shot 2021-08-23 at 3 15 15 PM](https://user-images.githubusercontent.com/53324985/130504629-a0ae7f3e-92e1-4090-8398-78547b2f2206.png)

`ozone admin namespace dist /`
![Screen Shot 2021-08-23 at 3 16 14 PM](https://user-images.githubusercontent.com/53324985/130504718-706aa08b-a4b3-4045-a732-de540c6c1fb4.png)

cc @smengcl @avijayanhwx for reviews.

2021-08-24 04:52 UTC, smengcl commented on hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsUtils.java
> +  }
Can we combine two methods into one? It can check `isHttpSecurityEnabled` directly from `conf`.

2021-08-24 05:09 UTC, smengcl requested changes
Thanks for the patch!

Let's add an integration test (see `TestOzoneShellHA`) or a robot test (see `testOMAdminCmd.robot`) for the new shell commands as well.

2021-08-24 05:09 UTC, smengcl commented on hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/recon/ReconConfigKeys.java
> +      "ozone.recon.https-address";
We already have these in `ReconServerConfigKeys`. No need to add them here.
```suggestion
```

2021-08-24 05:09 UTC, smengcl commented on hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/DiskUsageSubCommand.java
> +
```suggestion
```

2021-08-24 18:34 UTC, smengcl commented on hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsUtils.java
> +    String name = conf.get(OZONE_RECON_HTTP_ADDRESS_KEY);
Yes. We need the port from `OZONE_RECON_HTTP_ADDRESS_KEY`/`OZONE_RECON_HTTPS_ADDRESS_KEY`.

The logic could be:

If address in `OZONE_RECON_HTTP_ADDRESS_KEY`/`OZONE_RECON_HTTPS_ADDRESS_KEY` is set, we should use the address from them.

But if address in `OZONE_RECON_HTTP_ADDRESS_KEY`/`OZONE_RECON_HTTPS_ADDRESS_KEY` is **not** set, we should just fallback to the address from `OZONE_RECON_ADDRESS_KEY`. And use the default port in this case.

2021-08-24 18:41 UTC, yuangu002 commented on hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsUtils.java
> +    String name = conf.get(OZONE_RECON_HTTP_ADDRESS_KEY);
Can we assume default port is 9888 and 9889 for HTTP and HTTPs?

2021-08-24 23:46 UTC, avijayanhwx commented on hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/NSSummaryCLIUtils.java
> +    int idx = path.indexOf("/", OFS_PREFIX.length());
ofs:// path takes in OM host:port or service id as the first part after the ofs:// prefix. Hence, this code needs to handle that as well.

2021-08-24 23:46 UTC, avijayanhwx commented on hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsUtils.java
> +  public static InetSocketAddress getReconHTTPSAddresses(
Seems to have common logic with last method, maybe single method is good?

2021-08-24 23:46 UTC, avijayanhwx commented on hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/NSSummaryCLIUtils.java
> +    int idx = path.indexOf("/", OFS_PREFIX.length());
ofs:// path takes in service id or om host as the first part. This logic needs to strip out that as well.

2021-08-24 23:46 UTC, avijayanhwx commented on hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/NSSummaryAdmin.java
> +    if (OzoneSecurityUtil.isHttpSecurityEnabled(conf)) {
Need to look at ozone.http.policy to determine http vs https here.

2021-08-24 23:49 UTC, avijayanhwx commented
Thanks for working on this @yuangu002. Patch looks great. A few comments inline.

2021-08-25 15:43 UTC, yuangu002 commented
Addressed comments. Moved du percentage to hoverinfo in frontend in order to avoid text overlapping.
PTAL.

2021-08-25 16:19 UTC, smengcl commented on hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/NSSummaryAdmin.java
> +    return getHttpPolicy(conf) == HttpConfig.Policy.HTTPS_ONLY;
`|| this == HttpConfig.Policy.HTTP_AND_HTTPS`

Also, why not use `getHttpPolicy(conf).isHttpsEnabled()` directly?

https://github.com/apache/ozone/blob/79a9d39da7f33e71bc00183e280105562354cca4/hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/HttpConfig.java#L59

2021-08-25 16:21 UTC, smengcl commented on hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/recon/ReconConfigKeys.java
> +      "0.0.0.0:9889";
Reorder the variables. Make them in the order of KEY / DEFAULT / KEY / DEFAULT / KEY / DEFAULT.

2021-08-25 16:24 UTC, smengcl commented on hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/recon/ReconConfigKeys.java
> +      "recon:9891";
Recon RPC address default host should not be `recon`. This default value isn't just for the testing environment. `0.0.0.0` should allow Recon server to start up normally and listen on all interfaces.

But we should expect admins to set this address properly for **clients**.

```suggestion
      "0.0.0.0:9891";
```

2021-08-28 05:11 UTC, smengcl commented
CI is green. Will merge shortly.

2021-08-28 05:12 UTC, merged

2021-08-28 05:12 UTC, smengcl commented
Thanks @yuangu002 for the patch. Thanks @avijayanhwx for reviewing.