HDDS-6206. Application errors must not flood system log
apache/ozone pull request #3001
Opened 2022-01-19 11:04 UTC by kuenishi

## What changes were proposed in this pull request?

Frequent errors such as NoSuchBucket or NoSuchKey must not write down error logs. They should be in audit logs in principles. Otherwise, we may miss important errors like NullPointerException that does not appear in healthy system. To make sure that we can keep eyes on system health than access by applications, errors that stem from applications must not be printed in normal log files.

## What is the link to the Apache JIRA

HDDS-6206

## How was this patch tested?

Unit tests by CI

2022-02-02 12:38 UTC, adoroszlai requested changes
Thanks @kuenishi for the patch.  I think it's a good change to have.  Can you please make the debug-level log call conditional?

2022-02-03 02:18 UTC, kuenishi commented
@adoroszlai Thanks for review. I committed your proposal.

2022-02-03 05:09 UTC, adoroszlai approved these changes

2022-02-03 05:09 UTC, merged

2022-02-03 05:09 UTC, adoroszlai commented
Thanks @kuenishi for updating the patch.