HDDS-7102. Exclude unnecessary RangerClient dependencies
apache/ozone pull request #3669
Opened 2022-08-09 22:00 UTC by smengcl

## What changes were proposed in this pull request?

Exclude:

```
com.amazonaws:aws-java-sdk-bundle
org.apache.hive:hive-storage-api
org.apache.kafka:kafka-clients
org.apache.solr:solr-solrj
```

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-7102

## How was this patch tested?

- [ ] All existing tests should pass.
- [ ] Ensure `RangerClient` would still function as expected.

2022-08-15 15:20 UTC, adoroszlai requested changes
Thanks @smengcl for working on this.  Tarball size is reduced to 305M, which looks much better.

2022-08-15 18:29 UTC, smengcl commented on hadoop-ozone/dist/src/main/license/bin/LICENSE.txt
> +   net.java.dev.jna:jna-platform
Ah. I actually misread its LICENSE. I thought it was LGPL only after 2.1.

Done

2022-08-15 19:56 UTC, adoroszlai approved these changes
Thanks @smengcl for updating the patch.

2022-08-15 19:57 UTC, merged

2022-08-18 06:16 UTC, smengcl commented
Thanks @adoroszlai for reviewing and merging this.