HDDS-7088. Removed IOException with log level warn
apache/ozone pull request #3809
Opened 2022-10-07 12:11 UTC by navinko

## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## What is the link to the Apache JIRA

(Please create an issue in ASF JIRA before opening a pull request,
and you need to set the title of the pull request which starts with
the corresponding JIRA issue number. (e.g. HDDS-XXXX. Fix a typo in YYY.)

Please replace this section with the link to the Apache JIRA)

## How was this patch tested?

(Please explain how this patch was tested. Ex: unit tests, manual tests)
(If this patch involves UI changes, please attach a screen-shot; otherwise, remove this)

2022-10-07 16:43 UTC, navinko commented
Hi @szetszwo added the suggested changes.  Kindly review the PR 
Thanks

2022-10-07 19:19 UTC, myskov commented
Hi @navinko. As far as I understand the jira, the issue is not that OM doesn't start but the raft directory gets overridden (by OM or SCM, dependent on whom started later). In this case, OM should not be started.
It seems that the fix to the issue should allow sharing ratis dir by OM and SCM.

2022-10-07 19:21 UTC, myskov reviewed
Hi @navinko. As far as I understand the jira, the issue is not that OM doesn't start but the raft directory gets overridden (by OM or SCM, dependent on whom started later). In this case, OM should not be started.
It seems that the fix to the issue should allow sharing ratis dir by OM and SCM.

2022-10-10 06:19 UTC, szetszwo commented
> ... raft directory gets overridden (by OM or SCM, dependent on whom started later) ...

@myskov , an existing raft directory should never be overridden automatically since it may cause data loss.  Currently, it throws an exception and stop starting.  After this change, it will print a warning and use a different directory because the group ids are different.

2022-10-10 07:17 UTC, szetszwo approved these changes
+1 the change looks good.

Will wait for the build to be completed.

2022-10-10 08:55 UTC, navinko commented
Thanks @szetszwo @myskov for suggestions and reviewing .

2022-10-10 12:36 UTC, myskov commented
> > ... raft directory gets overridden (by OM or SCM, dependent on whom started later) ...
> 
> @myskov , an existing raft directory should never be overridden automatically since it may cause data loss. Currently, it throws an exception and stop starting. After this change, it will print a warning and use a different directory because the group ids are different.

Ok, but in this case, the warning message is misleading, and it should be changed.

2022-10-10 12:41 UTC, myskov requested changes

2022-10-10 12:49 UTC, szetszwo commented
@myskov , you are right that the message is misleading.

@navinko , could you update the error message?

2022-10-10 12:49 UTC, myskov commented
Let me explain the reasoning behind the requested change. We use Ozone in production and our administrators would be very concerned by the warning: "Ratis group Dir on disk scm does not match with RaftGroupID7f6848f2-63c2-3ce4-a1d2-9e88065dfcc3 generated from service id ozone1. Looks like there is a change to ozone.om.service.ids value after the cluster is setup. Currently change to this value is not supported."
It sounds like a fatal error, not a warning.

2022-10-10 18:24 UTC, navinko commented
Thanks @szetszwo @myskov for reviewing . I have updated the PR

2022-10-10 21:22 UTC, kerneltime commented
@navinko why should the exception be dropped? An incorrectly configured OM and SCM folder should be a catastrophic failure.

2022-10-11 04:48 UTC, navinko commented
Hi @kerneltime , In my understanding it's very common in production that SCM and OM wud be collocated and in current design if both the scm and om ratis directory shared and if which ever is started later , it will not just override the existing Raft directory as there will be data loss so it throws an exception and stop starting. After this change, it will print a warning and  create a new directory because the group ids are different.

2022-10-11 07:54 UTC, szetszwo commented
> ... In my understanding it's very common in production that SCM and OM wud be collocated ...

Indeed, it is uncommon in production (SCM and OM usually use different directories, or even different machine) but it may happen in testing setup.

2022-10-11 07:56 UTC, szetszwo commented on hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
> +              LOG.warn("Another ratis dir is detected "
@navinko , Please include the name `ratisGroupDir.getName()`.

2022-10-11 09:46 UTC, szetszwo commented on hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
> +              LOG.warn("Another ratis dir is detected "
@navinko , thanks for the update.  Let's use a similar message for both cases
```java
@@ -1353,16 +1353,13 @@ private void initializeRatisDirs(OzoneConfiguration conf) throws IOException {
         for (File ratisGroupDir : ratisDirFiles) {
           if (ratisGroupDir.isDirectory()) {
             if (!ratisGroupDir.getName().equals(groupIDfromServiceID)) {
-              throw new IOException("Ratis group Dir on disk "
-                  + ratisGroupDir.getName() + " does not match with RaftGroupID"
-                  + groupIDfromServiceID + " generated from service id "
-                  + getOMServiceId() + ". Looks like there is a change to " +
-                  OMConfigKeys.OZONE_OM_SERVICE_IDS_KEY + " value after the " +
-                  "cluster is setup. Currently change to this value is not " +
-                  "supported.");
+              LOG.warn("Unknown directory {} exists in ratis storage dir {}."
+                  + " It is recommended not to share the ratis storage dir.",
+                  ratisGroupDir, omRatisDir);
             }
           } else {
-            LOG.warn("Unknown file {} exists in ratis storage dir {}",
+            LOG.warn("Unknown file {} exists in ratis storage dir {}. "
+                + " It is recommended not to share the ratis storage dir.",
                 ratisGroupDir, omRatisDir);
           }
         }
```

2022-10-11 11:10 UTC, szetszwo approved these changes
+1 the change looks good.

2022-10-12 07:36 UTC, merged

2022-10-12 07:49 UTC, navinko commented
Thanks @szetszwo @myskov @kerneltime for reviewing the PR.