HDDS-7575. Correct showing of RATIS-THREE icon in Recon UI
apache/ozone pull request #4026
Opened 2022-12-01 14:59 UTC by symious

## What changes were proposed in this pull request?

This bug in introduced in [HDDS-6308](https://issues.apache.org/jira/browse/HDDS-6308), which updates the type of "replicationFactor" from "number" to "string".

This ticket is to fix this issue.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-7575

## How was this patch tested?

<img width="739" alt="image" src="https://user-images.githubusercontent.com/14933944/205085892-8c266a52-03ec-4068-a16e-17f70d6e33de.png">

2022-12-01 17:35 UTC, kaijchen approved these changes
LGTM

2022-12-01 18:04 UTC, kaijchen requested changes
Fix CI failure.

2022-12-01 18:04 UTC, kaijchen commented on hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/utils/themeIcons.tsx
> +    const textClass = replicationFactor == "THREE" ? threeFactorClass : 'icon-text-one-dot';
```suggestion
    const textClass = replicationFactor === "THREE" ? threeFactorClass : 'icon-text-one-dot';
```

2022-12-02 02:38 UTC, kaijchen commented
Thanks @symious for the fix.

2022-12-02 02:39 UTC, merged

2022-12-02 02:39 UTC, symious commented
@kaijchen Thanks for the review.