HDDS-7850. disable depcheck in hadoop-ozone until the deps of ranger and zookeeper converge
apache/ozone pull request #4218
Opened 2023-01-29 09:58 UTC by JacksonYao287

## What changes were proposed in this pull request?

the system info of my macbook is as follow:

Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T23:06:16+08:00)
Maven home: /Library/apache-maven-3.6.2
Java version: 1.8.0_362, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk@8/1.8.0+362/libexec/openjdk.jdk/Contents/Home/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "mac os x", version: "12.6", arch: "x86_64", family: "mac"

 

when building the project on my macbook, this error comes out.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (depcheck) on project ozone-manager: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]

the reason is :

[INFO] — maven-enforcer-plugin:3.0.0-M1:enforce (depcheck) @ ozone-manager —
[WARNING]
Dependency convergence error for org.apache.httpcomponents:httpasyncclient:4.1.4 paths to dependency are:
+-org.apache.ozone:ozone-manager:1.4.0-SNAPSHOT
  +-org.apache.ranger:ranger-intg:2.3.0
    +-org.apache.ranger:ranger-plugins-common:2.3.0
      +-org.apache.ranger:ranger-plugins-audit:2.3.0
        +-org.elasticsearch.client:elasticsearch-rest-client:7.6.0
          +-org.apache.httpcomponents:httpasyncclient:4.1.4
and
+-org.apache.ozone:ozone-manager:1.4.0-SNAPSHOT
  +-org.apache.ranger:ranger-intg:2.3.0
    +-org.apache.ranger:ranger-plugins-common:2.3.0
      +-org.apache.ranger:ranger-plugins-audit:2.3.0
        +-org.apache.httpcomponents:httpasyncclient:4.1.3

[WARNING]
Dependency convergence error for org.apache.zookeeper:zookeeper-jute:3.5.6 paths to dependency are:
+-org.apache.ozone:ozone-manager:1.4.0-SNAPSHOT
  +-org.apache.ozone:hdds-hadoop-dependency-server:1.4.0-SNAPSHOT
    +-org.apache.hadoop:hadoop-common:3.3.4
      +-org.apache.zookeeper:zookeeper:3.5.6
        +-org.apache.zookeeper:zookeeper-jute:3.5.6
and
+-org.apache.ozone:ozone-manager:1.4.0-SNAPSHOT
  +-org.apache.ranger:ranger-intg:2.3.0
    +-org.apache.ranger:ranger-plugins-common:2.3.0
      +-org.apache.ranger:ranger-plugins-audit:2.3.0
        +-org.apache.solr:solr-solrj:8.6.3
          +-org.apache.zookeeper:zookeeper-jute:3.5.7

[WARNING]
Dependency convergence error for org.apache.httpcomponents:httpmime:4.5.10 paths to dependency are:
+-org.apache.ozone:ozone-manager:1.4.0-SNAPSHOT
  +-org.apache.ranger:ranger-intg:2.3.0
    +-org.apache.ranger:ranger-plugins-common:2.3.0
      +-org.apache.ranger:ranger-plugins-audit:2.3.0
        +-org.apache.solr:solr-solrj:8.6.3
          +-org.apache.httpcomponents:httpmime:4.5.10
and
+-org.apache.ozone:ozone-manager:1.4.0-SNAPSHOT
  +-org.apache.ranger:ranger-intg:2.3.0
    +-org.apache.ranger:ranger-plugins-common:2.3.0
      +-org.apache.ranger:ranger-plugins-audit:2.3.0
        +-org.apache.httpcomponents:httpmime:4.5.6

[WARNING]
Dependency convergence error for com.carrotsearch:hppc:0.8.1 paths to dependency are:
+-org.apache.ozone:ozone-manager:1.4.0-SNAPSHOT
  +-org.apache.ranger:ranger-intg:2.3.0
    +-org.apache.ranger:ranger-plugins-common:2.3.0
      +-org.apache.ranger:ranger-plugins-audit:2.3.0
        +-org.elasticsearch:elasticsearch:7.6.0
          +-com.carrotsearch:hppc:0.8.1
and
+-org.apache.ozone:ozone-manager:1.4.0-SNAPSHOT
  +-org.apache.ranger:ranger-intg:2.3.0
    +-org.apache.ranger:ranger-plugins-common:2.3.0
      +-org.apache.ranger:ranger-plugins-audit:2.3.0
        +-com.carrotsearch:hppc:0.8.0

[WARNING]
Dependency convergence error for org.apache.httpcomponents:httpcore-nio:4.4.12 paths to dependency are:
+-org.apache.ozone:ozone-manager:1.4.0-SNAPSHOT
  +-org.apache.ranger:ranger-intg:2.3.0
    +-org.apache.ranger:ranger-plugins-common:2.3.0
      +-org.apache.ranger:ranger-plugins-audit:2.3.0
        +-org.elasticsearch.client:elasticsearch-rest-client:7.6.0
          +-org.apache.httpcomponents:httpcore-nio:4.4.12
and
+-org.apache.ozone:ozone-manager:1.4.0-SNAPSHOT
  +-org.apache.ranger:ranger-intg:2.3.0
    +-org.apache.ranger:ranger-plugins-common:2.3.0
      +-org.apache.ranger:ranger-plugins-audit:2.3.0
        +-org.apache.httpcomponents:httpcore-nio:4.4.6

seems the deps of ranger and zookpeer does not converge for now, so we need to disable this depcheck to avoid building failure and report this to ranger and zookeeper community.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-7850

## How was this patch tested?

after disable depcheck in hadoop-zone, building succeed

2023-01-29 10:17 UTC, adoroszlai commented
@JacksonYao287, we don't see this problem in CI, nor can I reproduce it locally.  The transitive dependencies of Ranger that appear in your tree are excluded in `ozone-manager` POM.  Please check your local environment (maybe Maven needs to be upgraded).

2023-01-30 14:05 UTC, adoroszlai requested changes
We should not revert this part of HDDS-7372 to fix a local build issue.

2023-01-31 02:12 UTC, JacksonYao287 commented
> We should not revert this part of [HDDS-7372](https://issues.apache.org/jira/browse/HDDS-7372) to fix a local build issue.

i ask some of my coworkers to try to build the mainline ozone project on their macbooks (the Darwin Kernel Version 21.6.0), and the same error happens agains. this build issue can be reproduced on macbook with Darwin operating system. so , seems this build error is not caused by my local environment, it depends on operating system.

2023-01-31 08:24 UTC, adoroszlai commented
@JacksonYao287 As I mentioned, the dependencies in your tree (`elasticsearch` and `solr`), e.g.:

```
+-org.apache.ozone:ozone-manager:1.4.0-SNAPSHOT
  +-org.apache.ranger:ranger-intg:2.3.0
    +-org.apache.ranger:ranger-plugins-common:2.3.0
      +-org.apache.ranger:ranger-plugins-audit:2.3.0
        +-org.elasticsearch.client:elasticsearch-rest-client:7.6.0
          +-org.apache.httpcomponents:httpasyncclient:4.1.4
```

should be excluded by:

https://github.com/apache/ozone/blob/3393354472a02da9364dbf4f0da34f127eb4895d/hadoop-ozone/ozone-manager/pom.xml#L172-L203

Please try to debug the issue.  (Some ideas: Use `mvn --debug`.  Try building Ozone on Linux in a Docker container or VM.  If you have any network proxy, disable it.  Delete Ozone and/or Ranger artifacts from your `~/.m2/repository`.)

2023-02-02 06:25 UTC, JacksonYao287 commented
@adoroszlai after deep diving into to this issue, i find it is caused by maven-enforcer-plugin.
the version used by current mainline code is `3.0.0-M1`, which is released at Jul 26, 2017. maybe it is too old.
i update it to the latest version, it works well.
please take a look at  [this page](https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-enforcer-plugin)

2023-02-02 07:31 UTC, adoroszlai approved these changes
Thanks @JacksonYao287 for finding the fix.

(My guess is the problem is network-related, not OS-specific.)

2023-02-02 16:46 UTC, merged

2023-02-03 02:20 UTC, JacksonYao287 commented
thanks @adoroszlai for review and merge