HDDS-8619. hadoop fs operations using ofs:// fails with ClassNotFoundException ProtocolMessageEnum
apache/ozone pull request #4709
Opened 2023-05-13 09:12 UTC by swamirishi

## What changes were proposed in this pull request?

Adding hadoop-client-runtime to ozone dist to add jar in classpath when build is triggered without shading.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-8619

## How was this patch tested?
Manual testing adding jar in classpath

2023-05-13 09:30 UTC, adoroszlai requested changes

2023-05-13 09:30 UTC, adoroszlai commented on hadoop-ozone/dist/pom.xml
> +          <artifactId>hadoop-client-runtime</artifactId>
This is expected to be provided by users, similar to other Hadoop dependencies.

2023-05-14 10:26 UTC, adoroszlai requested changes
The same build of Ozone should include both `ozone-filesystem-hadoop[23]` and `ozone-filesystem-hadoop3-client`.  Users should choose one of these based on their environment.

`-DskipShade` is only for faster dev workflow, does not affect Ozone build/release.

2023-05-14 10:28 UTC, closed without merging

2023-05-15 04:15 UTC, kerneltime commented
+1 to what @adoroszlai said. The problem is in the classpath calculations by services dependent on Ozone.