HDDS-8758. Container replication to use DISK volumes
apache/ozone pull request #4857
Opened 2023-06-08 11:31 UTC by Cyrill

## What changes were proposed in this pull request?

Now there is a way to define a volume choosing policy for replicating closed containers only. 
Also added a policy that selects nodes with enough space on DISK/SSD storage - to be able to replicated closed containers on nodes with HDD.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-8758

## How was this patch tested?
unit tests, manual tests

2023-06-09 07:12 UTC, vtutrinov requested changes

2023-06-09 10:14 UTC, sodonnel commented
I only quickly looked over the code, but I was wondering how this is intended to be used?

There doesn't seem to be any way to direct certain containers to SSD / RAM / HDD? It appears you set the placement policy on all or some DNs to be SSD / HDD and then only on replication the containers will goto that type of disk on the target DN. Replication only happens if something goes wrong on the cluster (eg node goes down, unhealthy container etc) or the balancer is run. If open containers are created on HDD and then the replication policy says SSD, containers are just going to be on a mixture of disk types with no real control over where they are going or when they might move some replicas to a different storage type.

I wonder if we need a wider design around storage policies, as it is a more difficult problem in Ozone than in HDFS. For example in HDFS a block is a standalone entity associated with a file. That file can have a storage policy set against it. In Ozone, a block is in a container which is shared by many different keys of the same replication type. It is not so simple to say a given key should be marked HOT or Archive it affects the entire contents of the container.

I also think there is some parallel work going on with the data temperature heat map, and using that to move containers around, but I don't think I have seen anything about how that heat map is going to deal with containers holding a mix of hot / cold / archive data.

2023-06-14 15:19 UTC, vtutrinov commented
@sodonnel design doc of the feature is [here](https://docs.google.com/document/d/1TJBER84F07fTx-LUKiiXn9CCBpvKtpNJw9LDRIoubxU/edit#heading=h.usl6g0n0hvch)
The following PR to be discussed is - https://github.com/apache/ozone/pull/4895

2023-06-20 02:28 UTC, guohao-rosicky commented
Can ssd be temporary storage and call disk balance to move the container on ssd to hdd when the container is shut down. I think an option can be added for configuration

2023-06-20 07:30 UTC, vtutrinov commented
@guohao-rosicky This is the plan we're following:
1. Write new data to SSD
2. Move closed containers to DISK (HDD) volumes
3. Replicate the containers from (e.g.) broken datanodes to HDD volumes of healthy ones

2023-10-15 16:49 UTC, adoroszlai commented
/pending

2023-11-06 00:15 UTC, closed without merging

2024-04-10 03:31 UTC, guohao-rosicky commented
> @guohao-rosicky This is the plan we're following:
> 
> 1. Write new data to SSD
> 2. Move closed containers to DISK (HDD) volumes
> 3. Replicate the containers from (e.g.) broken datanodes to HDD volumes of healthy ones

@vtutrinov @Cyrill Do you want to continue this task? That's a great idea.