HDDS-8997. Fix RangerOzoneAuthorizer initialization issue.
apache/ozone pull request #5056
Opened 2023-07-13 02:27 UTC by ashishkumar50

## What changes were proposed in this pull request?

External access authorizer can be shared in same service. In case of ranger we can see we initialize multiple times in same service which eventually does refresh policies internally inside ranger plugin. Any request at this point doesn't work as policy check returns null. Which can be avoided by initialize only once during OM startup. 

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-8997

## How was this patch tested?

Run existing tests.

2023-07-13 02:27 UTC, ashishkumar50 commented
@smengcl, Please help to review.

2023-07-13 04:00 UTC, smengcl commented on hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataReader.java
> +          clazz.getSimpleName().equals("OzoneNativeAuthorizer")) {
```suggestion
          clazz.getSimpleName().equals(OzoneNativeAuthorizer.class.getSimpleName())) {
```

2023-07-13 04:03 UTC, smengcl commented on hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataReader.java
> +        accessAuthorizer = ozoneManager.getAccessAuthorizer();
Looks like `accessAuthorizer` isn't closed or destroyed upon `OmMetadataReader` instance closure. Should be fine to share it like this IMO.

2023-07-13 04:18 UTC, ashishkumar50 commented on hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataReader.java
> +          clazz.getSimpleName().equals("OzoneNativeAuthorizer")) {
Done

2023-07-13 04:19 UTC, smengcl approved these changes
lgtm pending CI

2023-07-14 08:46 UTC, adoroszlai requested changes
Thanks @ashishkumar50 for working on this.  While the patch is fine to minimize change, I think it would be better to let `OzoneManager` create and store `accessAuthorizer` just before creation of `OmMetadataReader`:

https://github.com/apache/ozone/blob/300e7a76481480ae2651ff7214d7b9f146091e68/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java#L828-L829

Then `OmMetadataReader` could simply store reference to `ozoneManager.getAccessAuthorizer()` without complex logic.

https://github.com/apache/ozone/blob/300e7a76481480ae2651ff7214d7b9f146091e68/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataReader.java#L96-L97

2023-07-14 08:46 UTC, adoroszlai commented on hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataReader.java
> +                          boolean bNeedAccessAuthInitialization) {
Nit: please don't prefix variables with type.

2023-07-14 09:55 UTC, ashishkumar50 commented
> Thanks @ashishkumar50 for working on this. While the patch is fine to minimize change, I think it would be better to let `OzoneManager` create and store `accessAuthorizer` just before creation of `OmMetadataReader`:
> 
> https://github.com/apache/ozone/blob/300e7a76481480ae2651ff7214d7b9f146091e68/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java#L828-L829
> 
> Then `OmMetadataReader` could simply store reference to `ozoneManager.getAccessAuthorizer()` without complex logic.
> 
> https://github.com/apache/ozone/blob/300e7a76481480ae2651ff7214d7b9f146091e68/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataReader.java#L96-L97

@adoroszlai, Thanks for the review, We can create and store `accessAuthorizer` in `OzoneManager`, but problem is for `nativeAuthorizer` which always need new instance.

2023-07-14 10:24 UTC, adoroszlai commented
> problem is for `nativeAuthorizer` which always need new instance.

Ah, OK, sorry, I missed that part.

2023-07-14 10:27 UTC, merged

2023-07-14 10:27 UTC, adoroszlai commented
Thanks @ashishkumar50 for the patch, @smengcl for the review.