HDDS-9199. Snapshot chain corruption should not fail OM restart
apache/ozone pull request #5262
Opened 2023-09-08 18:28 UTC by hemantk-12

## What changes were proposed in this pull request?
Currently, OM restart fails and leaves the OM in unstable (which can't be stabilized without manual effort) if there is any kind of failure in snapshot chain reconstruction. Previous issues ([HDDS-7689](https://issues.apache.org/jira/browse/HDDS-7689), [HDDS-8530](https://issues.apache.org/jira/browse/HDDS-8530), [HDDS-8832](https://issues.apache.org/jira/browse/HDDS-8832) and [HDDS-9073](https://issues.apache.org/jira/browse/HDDS-9073)) where OM restart failed and left it in unstable state.

In this change, it is proposed to keep the snapshot chain state and let the OM start without any snapshot/chain related issues. Snapshot chain corrupted state is used to block all the snapshot's write operations like create, delete and purge snapshot if snapshot chain is corrupted.

A new parameter, `snapshotChainCorrupted`, is added to `SnapshotChainManager` to keep the state if chain is loaded successfully or not. It is used in access methods `addSnapshot()` to chain, `deleteSnapshot()` from chain and few others before returning response to the caller. In case of chain corruption, `addSnapshot()`, `deleteSnapshot()` will throw `IllegalStateException` and fail snapshot write operations.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-9199

## How was this patch tested?
Updated unit and integration tests.

2023-09-18 16:42 UTC, umamaheswararao commented
@swamirishi Could you also please take a look at it?

2023-10-04 14:23 UTC, smengcl commented on hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotCreateRequest.java
>      }
Is it intended that this exception is swallowed here?

2023-10-04 14:26 UTC, smengcl approved these changes
Thanks @hemantk-12 for taking care of this. lgtm

2023-10-04 14:43 UTC, swamirishi requested changes
thanks for the patch @hemantk-12. I guess we can just disable snapshots all together in case of snapshot corruption.
OzoneManager#isFilesystemSnapshotEnabled().

2023-10-04 17:28 UTC, hemantk-12 commented
> I guess we can just disable snapshots all together in case of snapshot corruption. OzoneManager#isFilesystemSnapshotEnabled(). Since snapdiff & deep clean should also not run.

1. `OzoneManager#isFilesystemSnapshotEnabled()` is based on ozone config. I don't think it is a good idea to leverage it for snapshot chain corruption. We can add something else but it would be similar to `SnapshotChainManager#snapshotChainCorrupted`.

2. Any operation relying on `SnapshotChainManager` should fail and would fail. If I'm not wrong, snapDiff, snapshot read and snapshot list don't rely on `SnapshotChainManager`. So I think it is OK to let them go. Regarding deep clean (or create snapshot), depends on  `SnapshotChainManager` because it is used to move keys around and cause snapshot corruption is wrong keys are moved. Deep clean will fail here: https://github.com/apache/ozone/blob/master/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/KeyDeletingService.java#L228 and similar for creation.

2023-10-04 17:31 UTC, merged

2023-10-04 17:32 UTC, hemantk-12 commented
Thanks @smengcl and @swamirishi for the review.