createKey dashboard added
apache/ozone pull request #6865
Opened 2024-06-25 19:44 UTC by muskan1012

## What changes were proposed in this pull request?
Created a new dashboard and added visualisations for all the required CreateKey Metrics.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-9977

## How was this patch tested?

The patch has been tested over a Grafana.

2024-06-26 06:46 UTC, tanvipenumudy reviewed
Thank you @muskan1012, for working on the patch. 

Could you please share snapshots to the added dashboards over the PR?
Here are a few references: [Dashboard for Chunks & Volume IO](https://github.com/apache/ozone/pull/6554), [S3 API-level Dashboard](https://github.com/apache/ozone/pull/6202)

2024-06-26 07:56 UTC, tanvipenumudy commented
@devabhishekpal could you also please take a look? Thanks!

2024-06-27 09:54 UTC, muskan1012 commented
Sure @tanvipenumudy, please find snapshot for the dashboards here:
![image](https://github.com/apache/ozone/assets/55579937/691a1ee3-c4e5-4987-b714-7181c9c7075d)
![image](https://github.com/apache/ozone/assets/55579937/f4e829c6-544e-4494-85fd-aa7c0cfc8ce4)

2024-06-27 17:04 UTC, tanvipenumudy requested changes
I have tested out the patch locally by setting up an Ozone docker-compose cluster with the monitoring add-ons, steps as outlined [here](https://github.com/apache/ozone/blob/master/hadoop-ozone/dist/src/main/compose/ozone/README.md#add-ons).

I noticed that a few charts weren't coming up for me. It appears there are `31` occurrences of hardcoded host values. Could you please fix the same?

Additionally, once the updates are made, could you also please ensure the snapshots (as to how the patch was tested) include all the charts added for the create keys dashboard?

2024-06-27 17:15 UTC, tanvipenumudy reviewed
Please find a few minor nits.

2024-06-27 17:15 UTC, tanvipenumudy commented on hadoop-ozone/dist/src/main/compose/common/grafana/dashboards/Ozone - CreateKey Metrics.json
> +      "title": "Om Check Access Latency Metrics",
```suggestion
      "title": "OM Check Access Latency Metrics",
```

2024-06-27 17:15 UTC, tanvipenumudy commented on hadoop-ozone/dist/src/main/compose/common/grafana/dashboards/Ozone - CreateKey Metrics.json
> +      "title": "Om Ugi Metrics",
```suggestion
      "title": "OM Ugi Metrics",
```

2024-07-08 13:20 UTC, tanvipenumudy approved these changes

2024-07-08 13:30 UTC, tanvipenumudy commented
Thank you @muskan1012 for working on the create keys dashboard, the changes LGTM.

This should be very helpful in diagnosing performance-related issues/regressions.

2024-07-08 13:31 UTC, merged